### ISSUE TITLE
Update to the latest version of twitchio

### ISSUE THREAD

**Issue by prosolis** [prosolis/music#3]
Update bot to latest release of twitchio. 

**EDIT

pip is now set to twitchio 2.6.0

Now just need to

- [ ] Validate that it completely works
- [ ] Move over to any new references or functions

**Comment by camcast3** [comment]
pip is now set to twitchio 2.6.0

Now just need to

- [ ] Validate that it completely works
- [ ] Move over to any new references or functions

**Comment by camcast3** [comment]
Didnt want closed

**Comment by camcast3** [comment]
Closing as we are writing this completely.
