### ISSUE TITLE
Weird text rendering issue on Twitch Mobile App

### ISSUE THREAD

**Issue by prosolis** [prosolis/music#43]
Current like message contains a lot of additional spaces when viewed on Twitch mobile app. Report from user:

```We can’t see it at web browsers, but twitch app for iPad shows it. There is message where spaces are replaced with dots: ```[Thanks.this.data.will.help.us.continue.bringing.the](https://thanks.this.data.will.help.us.continue.bringing.the/)…………best [music.to](https://music.to/).Prosolis.Radio

**Comment by camcast3** [comment]
[]()![Screenshot_20230808_112912_Twitch.jpg](https://github.com/prosolis/music/assets/70344584/7be4bba2-cbb8-4610-95c8-c4402b060ad3)

**Comment by camcast3** [comment]
Will raise this issue with twitchio but this seems like a Twitch platform bug

**Comment by prosolis** [comment]
https://github.com/prosolis/music/blob/2119790f88b4dac39bc64bd0a1984944221a271f/bots/twitch_bot.py#L68
