### ISSUE TITLE
Add automated MPD playlist randomization 

### ISSUE THREAD

**Issue by prosolis** [prosolis/music#7]
As an extra measure to keep the playlist fresh, let's add an automated playlist reshuffle function to the bot.

**Comment by camcast3** [comment]
Need more info. Does ```mpc random on not``` work?

**Comment by camcast3** [comment]
https://github.com/joshkunz/ashuffle/releases/tag/v3.14.1

Need to test this out to see if this is a viable solution

**Comment by camcast3** [comment]
Migrating this item under mpdbot
