### ISSUE TITLE
Music sanity check before stream start

### ISSUE THREAD

**Issue by prosolis** [prosolis/music#8]
One common issue that occurs are music files ending up in the library with empty metadata files such as song title, artist name, or replaygain tags. As the library grows, manually checking each file becomes tedious. The intent of this feature is implement a sort of 'last line of defense' sanity check to validate all songs have values in these fields before MPD playback start. 

- [x] Check if each file has artist name populated
- [x] Check if each file has song title populated

**Comment by camcast3** [comment]
As of now the only way I know how to do this via python is through mpdproxy and the music needs to be playing in order for me to do that. Do you have suggestions @prosolis?

**Comment by camcast3** [comment]
https://mutagen.readthedocs.io/en/latest/user/index.html

**Comment by camcast3** [comment]
Closing this as #36 addresses the first two boxes and the second two are covered in issue 9
